In [35]:
import numpy as np
import pandas as pd
import sklearn.linear_model as lm
import statsmodels.formula.api as smf
from sklearn.metrics import accuracy_score

import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
#Loading the dataset and lookig at the head to get an idea of the columns and variables
titanic_data=pd.read_csv('/Users/manasi/Desktop/titanic.csv')
titanic_data.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [14]:
#Developing a model 
mod = smf.ols(formula='survived~C(pclass)+sex', data=titanic_data)

In [15]:
res = mod.fit()
print(res.summary())

                            OLS Regression Results                            
Dep. Variable:               survived   R-squared:                       0.341
Model:                            OLS   Adj. R-squared:                  0.340
Method:                 Least Squares   F-statistic:                     225.5
Date:                Wed, 11 Apr 2018   Prob (F-statistic):          7.79e-118
Time:                        19:20:19   Log-Likelihood:                -639.22
No. Observations:                1309   AIC:                             1286.
Df Residuals:                    1305   BIC:                             1307.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept          0.8990      0.025     35.

In [25]:
#Predicting the res values
yhat=res.predict()
yhat

array([ 0.89898393,  0.39411348,  0.89898393, ...,  0.10147811,
        0.10147811,  0.10147811])

In [19]:
yhat.max()

0.89898393224477124

In [20]:
yhat.min()

0.10147811470358525

In [36]:
#Making an array of 0 and 1 for predicted values
new=(yhat > 0.5)+0
new

array([1, 0, 1, ..., 0, 0, 0])

In [37]:
#Calculating the accuracy score which comes up to 78%
accuracy_score(titanic_data['survived'],new)

0.77998472116119177

0.77998472116119177

In [45]:
mod1 = smf.ols(formula='survived~C(pclass)*sex', data=titanic_data)

In [46]:
res1 = mod1.fit()
print(res1.summary())

                            OLS Regression Results                            
Dep. Variable:               survived   R-squared:                       0.370
Model:                            OLS   Adj. R-squared:                  0.368
Method:                 Least Squares   F-statistic:                     153.2
Date:                Wed, 11 Apr 2018   Prob (F-statistic):          4.02e-128
Time:                        19:57:27   Log-Likelihood:                -609.86
No. Observations:                1309   AIC:                             1232.
Df Residuals:                    1303   BIC:                             1263.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Intercept           

The coeeficients of base intercept =0.9653
Probability of Class 1 female surviving is 0.9653
Probability of Class 2 female surviving is Intercept-0.0785
Probability of Class 3 female surviving is Intercept-0.4745

In [47]:
yhat1=res1.predict()
yhat1

array([ 0.96527778,  0.34078212,  0.96527778, ...,  0.15212982,
        0.15212982,  0.15212982])

In [48]:
new1=(yhat1 > 0.5)+0
new1

array([1, 0, 1, ..., 0, 0, 0])

In [49]:
#The accuracy comes up to 79%
accuracy_score(titanic_data['survived'],new1)

0.78304048892284184

The accuracy improved by 0.4 percent